# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ed291576a29a96dada562d1480a52492a37e562f14b14b6bc63090010a98443257430b3f2dd29b7bd7dc9812100bbcc1afc01d7fb930c43197fc54bbb08a6bdb

test:
  secret_key_base: 86cda1acb241b1212415857df9adce6b732d97497462b98a087a58bb1a5ed09d1e483aab85eed7ec36d8210bea95fd7ae415e782a52061d32be3666cb28e3410

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
